# travis build configuration for stm32plus

language: cpp
sudo: false

addons:
  apt:
    packages:
      libc6-i386
      scons

cache:
  directories:
    - $HOME/gcc-arm-none-eabi-7-2018-q2-update

env:
  - MODE=small MCU=f1mdvl HSE=8000000 LTO=no
  - MODE=small MCU=f1md HSE=8000000 LTO=no
  - MODE=small MCU=f1hd HSE=8000000 LTO=no
  - MODE=small MCU=f1cle HSE=25000000 LTO=no
  - MODE=small MCU=f051 HSE=8000000 LTO=no
  - MODE=small MCU=f030 HSE=8000000 LTO=no
  - MODE=small MCU=f042 HSE=8000000 LTO=no
  - MODE=small MCU=f4 HSE=8000000 LTO=no
  - MODE=small MCU=f4 HSE=8000000 FLOAT=hard LTO=no
  - MODE=small MCU=f429 HSE=8000000 LTO=no
  - MODE=small MCU=f429 HSE=8000000 FLOAT=hard LTO=no

install:
  - export GCC_DIR=$HOME/gcc-arm-none-eabi-7-2018-q2-update
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-g++ ]; then wget $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME; fi
  - export PATH=$PATH:$GCC_DIR/bin

script:
  - scons mode=$MODE mcu=$MCU hse=$HSE float=$FLOAT lto=$LTO install INSTALLDIR=~/usr -j4
  - cd ~/usr && find . | sort
